### PR TITLE
Adding OpenJS Architect

### PR DESCRIPTION
**Pull request by brianleroux**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rjlohan** [comment]
Please update the PR with some justification for this addition. I had a quick scan but this project only seems to relate to CloudFormation tangentially, not sure it's a good addition at this time.

**Comment by brianleroux** [comment]
oh hey @rjlohan sorry this wasn't clear! .arc is a high level format that generates cloudformation templates. it is literally the point the of the project! you can see a demonstration of this here https://arc.codes/playground

(the .arc file on the left creates the cfn on the right)

**Comment by rjlohan** [comment]
I see OK. Perhaps we can point at the GitHub repo as well as (or instead of) the HTTP site? That aligns with most of the rest of the guidance on this repo. How does this compare to CDK, which seems to have a similar purpose?

**Comment by brianleroux** [comment]
Not really sure why we'd point to the github instead of the documentation. This is a very different project than CDK. Perhaps the first thing to notice is that OpenJS Architect predates CDK by literal years. However you are correct in that they both share a desire to make authoring CloudFormation easier. They approach this goal in very different ways. Architect defines a high level declarative manifest file. `.arc`, `arc.json`, arc.yaml` or `arc.toml` and then compiles it into a CFN template. Otherwise completely 'native' CloudFormation. CDK creates imperative runtime bindings for various langauges compiles (synthesizes) into a CloudFormation template you never see. Neither approach is strictly better than the other but imperative code is usually considered less deterministic and harder to debug/maintain.

**Comment by rjlohan** [comment]
We want to encourage and foster open-source projects for this repository. It's not strictly a 100% rule, but since this project has an open-source foundation we'd prefer to link to that as the starting point. It also helps us determine the engagement on a project to judge as to whether a proposal warrants inclusion in this list.

In this case, I'm happy to include ARC, if we can change the link to the GitHub repo.

**Comment by brianleroux** [comment]
Sorry but I completely do not understand. 

Architect is as open as a project can be. Openly licensed (ASL2) and open governance since 2017. 

What is the problem with pointing at the website (which itself is hosted by the OpenJS Foundation which is a subsidiary of the Linux Foundation) ?

**Comment by brianleroux** [comment]
ok, maybe… you think the website arc.codes is some kind of propreitary thing? (it is not. its just docs for the open source project. my company and literally hundreds of others (probably thousands now) utilize architect every day and reference these docs. we can link to the repo but that just links back to this website.

**Comment by rjlohan** [comment]
> ok, maybe… you think the website arc.codes is some kind of propreitary thing? (it is not. its just docs for the open source project. my company and literally hundreds of others (probably thousands now) utilize architect every day and reference these docs. we can link to the repo but that just links back to this website.

Sure, I get that's the case, I'd just rather have some consistency in how we manage this list, as it'll be easier for us in the long run. There are other examples here - Former2 for example is also hosted at https://former2.com but we link to the underlying repo. I see that there's a 2-way link, would just rather we point this list at GitHub repos where available.

**Comment by brianleroux** [comment]
Ok updated based on your feedback hopefully this is better for your admin purposes… really just want to help best practices like CFN become more adopted!

**Comment by rjlohan** [comment]
Thanks Brian, appreciate your engagement and interest! 😄

**Pull request merged**
