### PR TITLE
Add Stackup to list of CLI tools

### PR DESCRIPTION
**Pull request by ps-jay**
*Issue #, if available:*
N/A

*Description of changes:*
Add Stackup to the list of CLI tools.

It's a nice tool that has two main verbs: `up` and `down`  (there are others as well, it supports change-sets for example).  These verbs are declarative and idempotent.

The `down` command succeeds if: the stack exists and successfully deletes, but also if the stack doesn't exist.

The `up` command succeeds if: the stack creates, or if the stack already exists and updates successfully, and also will cleanup/delete a 'create_failed' stack first.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by mrinaudo-aws — APPROVED** [review]
Thank you, @ps-jay !

**Review by mrinaudo-aws — CHANGES_REQUESTED** [review]
Thank you, @ps-jay - I had dismissed my previous, stale review.  Can you please resolve conflicts on this branch, and then ask for another review?  Thank you!

**Comment by ps-jay** [comment]
Done!

**Review by mrinaudo-aws — APPROVED** [review]
lgtm

**Pull request merged**
